### ISSUE TITLE
Self-hosted version showing "Staging Environment"

### ISSUE THREAD

**Issue by vivian940425** [BulletTrainHQ/bullet-train-docker#15]
Hi I just successfully started the self-hosted version, everything runs good but have couple questions

1. There's a sticky banner showing Staging Environment on the page. I am quite confused what does this mean? 
<img width="1307" alt="image" src="https://github.com/Flagsmith/self-hosted/assets/5315814/da628c54-f266-4d23-9b97-4ccdba8e088e">

2. On the bottom left side there's a quite hippy red text going on, kinda like a testing text?
<img width="418" alt="image" src="https://github.com/Flagsmith/self-hosted/assets/5315814/14ebcfde-0ee0-44fc-b660-60536789c2df">

Thank you so much!

**Comment by gagantrivedi** [comment]
That banner is actually controlled by one of the feature flag(butter_bar).  You can find more about it here: https://docs.flagsmith.com/deployment/overview#running-flagsmith-on-flagsmith
