### ISSUE TITLE
segments not working in self-hosted flagsmith

### ISSUE THREAD

**Issue by kevinr498** [BulletTrainHQ/bullet-train-docker#16]
https://flagsmith.github.io/flagsmith-charts/ helm deployment deployed, but segments aren't working. 

```
react-dom.production.min.js:187 TypeError: Cannot read properties of null (reading 'find')
    at Object.findOperator (utils.tsx:111:23)
```

**Comment by khvn26** [comment]
Closing in favour of https://github.com/Flagsmith/flagsmith-charts/issues/144 as @kevinr498 has confirmed that a pure Docker-based deployment works for them.
