### ISSUE TITLE
createsuperuser ".venv/bin/python: no such file or directory: unknown"

### ISSUE THREAD

**Issue by edumucelli** [BulletTrainHQ/bullet-train-docker#6]
First of all Flagsmith it is a great project. I am giving it a try on my local environment with docker-compose. As described in the documentation, once the docker-compose is up and running one can create an admin user by `docker-compose run --rm --entrypoint ".venv/bin/python src/manage.py createsuperuser" api`

Unfortunately when running it fails:

```
# Being at the this repository directory.
sudo docker-compose run --rm --entrypoint ".venv/bin/python src/manage.py createsuperuser" api          
Starting flagsmith_influxdb ... done
Starting flagsmith_postgres ... done
Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: ".venv/bin/python": stat .venv/bin/python: no such file or directory: unknown
```
I have worked around it either by replacing the `.venv` for the python binary directly:

```
sudo docker-compose run --rm --entrypoint "python src/manage.py createsuperuser" api
```

Or entering in the container and running it from there:

```
sudo docker exec -it flagsmith_api /bin/bash
cd app/src
python manage.py createsuperuser
```

Do you want me to make a PR to fix the documentation or am I missing something here?

**Comment by dabeeeenster** [comment]
Ah yes looks like a bug  - a PR would be great thanks!
